services:
  fastapi:
    build: ./backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/database_name
    depends_on:
      - db

  nextjs:
    build: ./frontend
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://fastapi:8000
    depends_on:
      - fastapi

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
